### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [tecnicojoao123/0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Faltou indicar qual página está ativa e também faltou alternar a cor da listagem das tarefas conforme o status. 

Para o primeiro ítem, bastaria criar uma classe `ativo` com o estilo de destaque e usá-lo no respective .html. Veja o exemplo para como ficaria considerando o `excluidas.html`. Para o segundo item, bastaria usar a mesma estratégia, veja nos comentários uma forma de diferenciar a listagem dos status. 

```html
<nav>
    <a class="pendentes" href="/pendentes.html">Pendentes</a>
    <a class="concluidas" href="/concluidas.html">Concluidas</a>
    <a class="ativa excluidas" href="/"class="ativa">Excluidas</a>
</nav>
```

**Nota:** 7

# Comentários

Notei que muitas das suas propriedades CSS são duplicadas entre as classes `pendentes` `concluidas` e `excluidas`. Você poderia criar uma classe mais genérica para armazenar essas propriedades e então fazer uso de duas classes. Veja no exemplo abaixo que é utilizada a classe `tarefa` junto com a classe `pendentes`. 

```html
<a class="tarefa pendentes" href="/pendentes.html">Pendentes</a>
``` 

O CSS ficaria assim: 

```css
.tarefa {
    font-family: sans-serif;
    color: rgb(250, 250, 250);
    font-size: 20px;
    border-style: solid;
    text-align: center;
    border-collapse: collapse;
    border-radius: 15px;
    padding: 3px 4px 4px 4px;
    text-decoration: none;
    border: 2px solid black;
    margin: 10px; 
    font-weight: bold; 
}

.pendentes {
    background: #8fd14f;
}

.concluidas {
    background: #0ca789;
}

.excluidas {
    background: #eb4045;
}
```

Você pode imaginar agora que `tarefa` possui três subvariações: `pendentes`, `concluidas` e `excluidas`.

```mermaid
flowchart LR;
  tarefa --> concluida;
  tarefa --> pendente;
  tarefa --> excluida;
```

Por fim, notei que o seu código está muito mal indentado. No VS Code você pode aplicar a formação automaticamente seguindo esses passos:
1. CTRL + P para abrir o executor de comandos
2. Digite "> Format Document"
